version: '3.8'

services:

  postgres-deadlinetracker:
    image: postgres:16
    container_name: postgres-deadlinetracker
    ports:
      - "${PORTDB1}:${PORTDB2}"
    environment:
      POSTGRES_USER: postgres-deadlinetracker
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: deadlinetracker
    volumes:
      - postgres_deadlinetracker_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    ports:
      - "${PORTBACKEND}:${PORTBACKEND}"
    env_file:
      - ./backend/.env
    container_name: backendtasks
    volumes:
      - whatsapp_session:/app/.wwebjs_auth
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    ports:
      - "${PORTFRONTEND}:80"
    env_file:
      - ./frontend/.env
    container_name: frontendtasks
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  whatsapp_session:
  postgres_deadlinetracker_data:
